"""Import a single POSIX Copy-as-cURL request as DATA, never execute it.

The entire metadata (including codex_listen_snapshot and its original JSON type)
is retained. The captured current user text is removed; historical/system context
is private. One atomic bundle prevents mixing credentials from unrelated imports.
"""
from copy import deepcopy
from dataclasses import dataclass, field
from datetime import datetime, timezone
import hashlib
import json
import re
import shlex
import uuid
from pathlib import Path
from urllib.parse import urlsplit
from .errors import DirectError, invalid
from .secure import MAX_FILE, ProcessLock, read_private, write_json

ORIGIN = 'https://prism.openai.com'
START_PATH = '/api/llm/response_with_tools_start'
STATUS_PATH = '/api/llm/response_with_tools_status'
HEARTBEAT_PATH = '/s/sandboxes/proxy/heartbeat'
REQUIRED_HEADERS = ('cookie', 'user-agent')
# Hop-by-hop/transport headers must be generated by HTTPX, not copied from DevTools.
DROP_HEADERS = {'host', 'content-length', 'connection', 'proxy-connection', 'transfer-encoding', 'accept-encoding', 'expect'}
HEADER_NAME = re.compile(r"^[!#$%&'*+.^_`|~0-9A-Za-z-]+$")


def strict_json(text: str):
    def pairs(items):
        d = {}
        for k, v in items:
            if k in d:
                raise ValueError('duplicate key')
            d[k] = v
        return d
    def bad_constant(_):
        raise ValueError('non-finite value')
    try:
        return json.loads(text, object_pairs_hook=pairs, parse_constant=bad_constant)
    except (ValueError, TypeError, RecursionError):
        raise invalid('invalid_json', 'Expected valid JSON without duplicate keys or non-finite numbers.') from None


def _ansi_quotes(command: str) -> str:
    """Decode Bash $'...' without eval; other POSIX quoting is left for shlex.

    Only escape sequences commonly emitted by DevTools are accepted. Shell
    substitutions are NEVER expanded. Unsupported encodings fail explicitly.
    """
    out, i, quote = [], 0, None
    simple = {'n': '\n', 'r': '\r', 't': '\t', 'b': '\b', 'f': '\f', 'v': '\v',
              'a': '\a', '\\': '\\', "'": "'", '"': '"'}
    while i < len(command):
        c = command[i]
        if quote is None and command.startswith("$'", i):
            i += 2
            decoded = []
            while i < len(command) and command[i] != "'":
                if command[i] != '\\':
                    decoded.append(command[i]); i += 1; continue
                i += 1
                if i >= len(command):
                    raise invalid('curl_quoting', 'Unterminated ANSI-C quote.')
                e = command[i]; i += 1
                if e in simple:
                    decoded.append(simple[e])
                elif e in 'xuU':
                    size = {'x': 2, 'u': 4, 'U': 8}[e]
                    digits = command[i:i+size]
                    if len(digits) != size or not re.fullmatch(r'[0-9a-fA-F]+', digits):
                        raise invalid('curl_quoting', 'Unsupported ANSI-C escape.')
                    try:
                        decoded.append(chr(int(digits, 16)))
                    except ValueError:
                        raise invalid('curl_quoting', 'Invalid Unicode escape.') from None
                    i += size
                elif e in '01234567':
                    digits = e
                    while i < len(command) and len(digits) < 3 and command[i] in '01234567':
                        digits += command[i]; i += 1
                    decoded.append(chr(int(digits, 8)))
                else:
                    raise invalid('curl_quoting', 'Unsupported ANSI-C escape; use Copy as cURL (bash).')
            if i >= len(command):
                raise invalid('curl_quoting', 'Unterminated ANSI-C quote.')
            out.append(shlex.quote(''.join(decoded))); i += 1; continue
        if c == '\\' and quote != "'" and i + 1 < len(command):
            out.append(command[i:i+2]); i += 2; continue
        if c in "'\"":
            if quote is None: quote = c
            elif quote == c: quote = None
        out.append(c); i += 1
    return ''.join(out)


def parse_curl(text: str) -> tuple[dict, dict]:
    if not isinstance(text, str) or len(text.encode('utf-8')) > MAX_FILE or '\x00' in text:
        raise invalid('curl_input', 'cURL text is invalid or too large.')
    clean = text.strip().lstrip('\ufeff').replace('\\\r\n', '').replace('\\\n', '')
    try:
        tokens = shlex.split(_ansi_quotes(clean), comments=False, posix=True)
    except ValueError:
        raise invalid('curl_quoting', 'Could not parse quoting; copy the complete cURL (bash) command.') from None
    if not tokens or tokens[0] != 'curl':
        raise invalid('curl_input', 'Expected one Copy-as-cURL (bash) command, not a script.')
    values = {'-H': 'header', '--header': 'header', '-b': 'cookie', '--cookie': 'cookie',
              '-A': 'ua', '--user-agent': 'ua', '-e': 'referer', '--referer': 'referer',
              '-X': 'method', '--request': 'method', '--url': 'url', '-d': 'data',
              '--data': 'data', '--data-raw': 'data', '--data-binary': 'data'}
    harmless = {'--compressed', '--http1.1', '--http2', '--silent', '--show-error', '-s', '-S', '-sS', '--globoff', '-g'}
    headers, body_text, url, method = {}, None, None, None

    def header(k, v):
        k = k.strip().lower(); v = v.strip()
        if not HEADER_NAME.fullmatch(k) or any(ord(c) < 32 or ord(c) == 127 for c in v):
            raise invalid('invalid_header', 'Captured header has invalid characters.')
        if k in headers and headers[k] != v:
            raise invalid('duplicate_header', 'Conflicting duplicate headers are not supported.')
        headers[k] = v

    i = 1
    while i < len(tokens):
        token = tokens[i]; i += 1
        if token in harmless: continue
        value = None; option = token
        if token.startswith('--') and '=' in token:
            option, value = token.split('=', 1)
        elif len(token) > 2 and token[:2] in {'-H', '-b', '-A', '-e', '-X', '-d'}:
            option, value = token[:2], token[2:]
        if option in values:
            if value is None:
                if i >= len(tokens): raise invalid('curl_input', 'cURL option is missing its value.')
                value = tokens[i]; i += 1
            kind = values[option]
            if kind == 'header':
                if ':' not in value: raise invalid('invalid_header', 'Expected a name:value header.')
                k, v = value.split(':', 1); header(k, v)
            elif kind in ('cookie', 'ua', 'referer'):
                if kind == 'cookie' and ('=' not in value or value.startswith('@')):
                    raise invalid('cookie_file_unsupported', 'Cookie file references are not supported.')
                header({'cookie':'cookie', 'ua':'user-agent', 'referer':'referer'}[kind], value)
            elif kind == 'method':
                if method is not None: raise invalid('curl_input', 'Duplicate HTTP method.')
                method = value
            elif kind == 'url':
                if url is not None: raise invalid('curl_input', 'Only one URL is supported.')
                url = value
            elif kind == 'data':
                if body_text is not None or value.startswith('@'):
                    raise invalid('curl_input', 'Expected one inline JSON body; file references are not read.')
                body_text = value
        elif token.startswith('https://') and url is None:
            url = token
        else:
            raise invalid('curl_option', 'Unsupported cURL option or shell syntax; no command was executed.')
    if url != ORIGIN + START_PATH or method not in (None, 'POST'):
        raise invalid('wrong_endpoint', 'Import a POST response_with_tools_start request from prism.openai.com only.')
    if body_text is None:
        raise invalid('missing_body', 'The captured start request must contain a JSON body.')
    body = strict_json(body_text)
    return headers, body


def _nonempty(value) -> bool:
    return isinstance(value, str) and bool(value.strip())


def validate_capture(headers: dict, body: dict) -> tuple[int, int]:
    if not isinstance(headers, dict) or not isinstance(body, dict):
        raise invalid('invalid_capture', 'Captured headers and body must be JSON objects.')
    for k in REQUIRED_HEADERS:
        if not _nonempty(headers.get(k)):
            raise invalid('incomplete_capture', f'Missing required captured header: {k}.')
    for k, v in headers.items():
        if not isinstance(k, str) or not HEADER_NAME.fullmatch(k) or not isinstance(v, str) or any(ord(c)<32 or ord(c)==127 for c in v):
            raise invalid('invalid_header', 'Invalid captured header.')
    if headers.get('origin', ORIGIN) != ORIGIN:
        raise invalid('wrong_origin', 'Captured Origin is not prism.openai.com.')
    if 'referer' in headers:
        ref = urlsplit(headers['referer'])
        if ref.scheme != 'https' or ref.netloc != 'prism.openai.com':
            raise invalid('wrong_origin', 'Captured Referer is not prism.openai.com.')
    if not headers.get('content-type', 'application/json').lower().startswith('application/json'):
        raise invalid('content_type', 'Only JSON start requests are supported.')
    metadata = body.get('metadata')
    if not isinstance(metadata, dict):
        raise invalid('missing_metadata', 'Captured start request has no metadata object.')
    for key in ('projectId', 'userId', 'sandbox_url', 'sandbox_token'):
        if not _nonempty(metadata.get(key)):
            raise invalid('incomplete_capture', f'Missing required captured metadata field: {key}.')
    if not _nonempty(body.get('conversationId')):
        raise invalid('incomplete_capture', 'Missing captured conversationId.')
    sb = urlsplit(metadata['sandbox_url'])
    if sb.scheme != 'https' or sb.netloc != 'prism.openai.com' or not (sb.path == '/s/sandboxes/proxy' or sb.path.startswith('/s/sandboxes/proxy/')) or sb.query or sb.fragment:
        raise invalid('sandbox_origin', 'Unsupported sandbox URL; do not substitute another host.')
    snapshot = metadata.get('codex_listen_snapshot')
    # Required by this peer-derived HTTP profile, not claimed universal Prism behavior.
    if not isinstance(snapshot, (dict, str)) or not snapshot:
        raise invalid('missing_snapshot', 'Capture is missing codex_listen_snapshot; copy a complete recent successful start request.')
    parsed = strict_json(snapshot) if isinstance(snapshot, str) else snapshot
    if not isinstance(parsed, dict):
        raise invalid('snapshot_schema', 'codex_listen_snapshot must encode a JSON object.')
    for aliases, expected in ((('project_id','projectId'), metadata['projectId']),
                              (('user_id','userId'), metadata['userId']),
                              (('conversation_id','conversationId'), body['conversationId'])):
        for key in aliases:
            if key in parsed and parsed[key] != expected:
                raise invalid('snapshot_identity', 'Snapshot and request identity conflict; recapture one complete request.')
    inputs = body.get('input')
    if not isinstance(inputs, list) or not inputs:
        raise invalid('input_schema', 'Expected captured input array.')
    positions = []
    for i, item in enumerate(inputs):
        if not isinstance(item, dict): raise invalid('input_schema', 'Invalid input item.')
        if item.get('role') == 'user' and item.get('type') == 'message':
            positions.append(i)
    if not positions:
        raise invalid('input_schema', 'No user message found in captured input.')
    user_index = positions[-1]
    if user_index != len(inputs)-1:
        raise invalid('input_schema', 'This text-only importer requires the last input item to be the current user message.')
    content = inputs[user_index].get('content')
    if not isinstance(content, list) or len(content) != 1 or not isinstance(content[0], dict) or content[0].get('type') != 'input_text' or not isinstance(content[0].get('text'), str):
        raise invalid('input_schema', 'The current user message must contain one input_text item.')
    return user_index, 0


@dataclass(repr=False)
class Bootstrap:
    import_id: str
    imported_at: str
    headers: dict = field(repr=False)
    template: dict = field(repr=False)
    user_index: int

    def __repr__(self):
        return f'Bootstrap(import_id={self.import_id!r}, secrets=<redacted>)'

    @property
    def metadata(self): return self.template['metadata']
    @property
    def conversation(self): return self.template['conversationId']
    @property
    def scope(self):
        b = json.dumps([self.metadata['userId'], self.metadata['projectId'], self.conversation], separators=(',',':')).encode()
        return hashlib.sha256(b).hexdigest()

    def payload(self, prompt: str) -> dict:
        body = deepcopy(self.template)
        body['input'][self.user_index]['content'][0]['text'] = prompt
        return body

    def request_headers(self) -> dict:
        result = {k: v for k, v in self.headers.items() if k not in DROP_HEADERS}
        result.setdefault('content-type', 'application/json')
        return result

    def to_json(self):
        return {'schema_version': 1, 'import_id': self.import_id, 'imported_at': self.imported_at,
                'source': ORIGIN + START_PATH, 'headers': self.headers, 'request_template': self.template}

    @classmethod
    def load(cls, path: Path):
        try:
            obj = strict_json(read_private(path).decode('utf-8'))
            if not isinstance(obj, dict) or obj.get('schema_version') != 1 or obj.get('source') != ORIGIN+START_PATH:
                raise invalid('bundle_schema', 'Unsupported bootstrap format; import a fresh cURL.')
            h, b = obj['headers'], obj['request_template']
            idx, _ = validate_capture(h,b)
            if not _nonempty(obj.get('import_id')) or not _nonempty(obj.get('imported_at')):
                raise invalid('bundle_schema', 'Bootstrap import identity is missing.')
            return cls(obj['import_id'], obj['imported_at'], h, b, idx)
        except (KeyError, UnicodeError, TypeError):
            raise invalid('bundle_schema', 'Invalid bootstrap format; import a fresh cURL.') from None


def import_curl(text: str, home: Path) -> Bootstrap:
    headers, body = parse_curl(text)
    idx, _ = validate_capture(headers, body)
    body = deepcopy(body)
    body['input'][idx]['content'][0]['text'] = ''
    bundle = Bootstrap(uuid.uuid4().hex, datetime.now(timezone.utc).isoformat(), headers, body, idx)
    # Validate completely BEFORE touching any existing bundle. Atomic single file.
    with ProcessLock(home):
        write_json(home / 'bootstrap.json', bundle.to_json())
    return bundle
